# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

repository: parkkimyun/parkkimyun.github.io

title: 서울과학고등학교 3기
email: seoulsciencehighschool.03@gmail.com
description: 서울과학고등학교 3기 홈피
#twitter_username: username
#github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : 서울과학고등학교
#  avatar           : "/assets/images/unju-logo-01.webp"
#  avatar           : "/assets/images/unju-logo-02.jpeg"
  avatar           : "/assets/images/sshs-logo-dark.webp"
  bio              : ""
#  location         : "Silicon Valley"
#  email            : seoulsciencehighschool.03@gmail.com
  links:
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/sshs-03/sshs-03.github.io"
    - label: "Email"
      icon: "fa-regular fa-envelope"
      url: "mailto:seoulsciencehighschool.03@gmail.com"
    - label: 바워
      icon: "fa-regular fa-hand-back-fist"
      url: "https://bawi.org/"
    - label: 서울과학고등학교
      icon: "fa-solid fa-school"
      url: "https://sshs.sen.hs.kr/"
    - label: 서울과학고등학교
      icon: "fa-solid fa-map-pin"
      url: "https://naver.me/G0DWOoVH"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/sshs-03/sshs-03.github.io"
    - label: "Email"
      icon: "fa-regular fa-envelope"
      url: "mailto:seoulsciencehighschool.03@gmail.com"
    - label: 바워
      icon: "fa-regular fa-hand-back-fist"
      url: "https://bawi.org/"
    - label: 서울과학고등학교
      icon: "fa-solid fa-school"
      url: "https://sshs.sen.hs.kr/"
    - label: 서울과학고등학교
      icon: "fa-solid fa-map-pin"
      url: "https://naver.me/G0DWOoVH"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      #classes: wide
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      #classes: wide
      layout: single
      author_profile: true

category:
  type: liquid
  path: /categories/
tag:
  type: liquid
  path: /tags/
